name: Reusable workflow

on:
  workflow_call:
    inputs:
      input_name:
        required: true
        type: string

jobs:
  workflow_1:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.run1.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with: 
          repository: melissafilomeno/gh-actions-poc
          ref: main
          sparse-checkout: |
            gh-actions-script.py
          sparse-checkout-cone-mode: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - run: pip install requests
      - id: run1
        shell: bash
        run: |
          {
            echo 'result<<EOF'
            python gh-actions-script.py --input1 ${{ inputs.input_name }} --github_token ${{ secrets.GITHUB_TOKEN }}
            echo EOF
          } >> "$GITHUB_OUTPUT"

  workflow_2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    needs: workflow_1
    steps:
      - uses: actions/checkout@v4
      - name: Write workflow_1 contents to file and create PR
        run: |
          echo ${{ inputs.input_name }}
          echo "value=`basename ${{ github.repository }}`"
          echo "${{ needs.workflow_1.outputs.result }}" >> "${{ inputs.input_name }}_output.txt"
          ls ${{ github.workspace }}
          cat "${{ inputs.input_name }}_output.txt"
          git config --global user.email "melissalfilomeno@gmail.com"
          git config --global user.name "MelissaFilomeno"
          git checkout -b "${{ inputs.input_name }}_branch"
          git add .
          git commit -m "add ${{ inputs.input_name }}_output.txt"
          git push -u origin "${{ inputs.input_name }}_branch"
          gh pr create --title "pr title" --body "pr body" --base main
        env:
            GH_TOKEN: ${{ github.token }}
