name: CI

on:
  workflow_call:
    inputs:
      input_name:
        required: true
        type: string

jobs:
  workflow_1:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.run1.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with: 
          repository: melissafilomeno/gh-actions-poc
          ref: main
          sparse-checkout: |
            gh-actions-script.py
          sparse-checkout-cone-mode: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - id: run1
        shell: bash
        run: |
          res=$(python gh-actions-script.py)
          res="${res//'%'/'%25'}"
          res="${res//$'\n'/'%0A'}"
          res="${res//$'\r'/'%0D'}"
          echo "::set-output name=result::$res"

  workflow_2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    needs: workflow_1
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ inputs.input_name }}
          echo "value=`basename ${{ github.repository }}`"
          echo "${{ needs.workflow_1.outputs.result }}" >> "output.txt"
          ls ${{ github.workspace }}
          cat "output.txt"
          git config --global user.email "melissalfilomeno@gmail.com"
          git config --global user.name "MelissaFilomeno"
          git checkout -b new_branch
          git add .
          git commit -m "write output file"
          git push -u origin new_branch
          gh pr create --title "pr title" --body "pr body" --base main
        env:
            GH_TOKEN: ${{ github.token }}
