name: CI

on:
  workflow_call:
    inputs:
      input_name:
        required: true
        type: string

jobs:
  workflow_1:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.run1.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with: 
          repository: melissafilomeno/gh-actions-poc
          ref: main
          sparse-checkout: |
            gh-actions-script.sh
          sparse-checkout-cone-mode: false
      - id: run1
        shell: bash
        run: |
          res=$( bash gh-actions-script.sh )
  
          echo "result<<EOF" >> "$GITHUB_OUTPUT"
          echo $res >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

  workflow_2:
    runs-on: ubuntu-latest
    needs: workflow_1
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ inputs.input_name }}
          echo "value=`basename ${{ github.repository }}`"
          echo "output1= ${{ needs.workflow_1.outputs.result }}" >> "output.txt"
          ls ${{ github.workspace }}
          cat "output.txt"
