name: CI

on:
  workflow_call:
    inputs:
      input_name:
        required: true
        type: string

jobs:
  workflow_1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v4
        with: 
          repository: melissafilomeno/gh-actions-poc
          ref: main
          sparse-checkout: |
            gh-actions-script.sh
          sparse-checkout-cone-mode: false
      - id: run1
        run: ./gh-actions-script.sh >> "$GITHUB_OUTPUT"

  workflow_2:
    runs-on: ubuntu-latest
    needs: workflow_1
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ inputs.input_name }}
          echo "value=`basename ${{ github.repository }}`"
          ls ${{ github.workspace }}
          echo "output1= ${{ needs.workflow_1.output.output1 }}"
